version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: tut_postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  memcached:
    image: memcached:1.6.9-alpine
    container_name: tut_memcached
    ports:
      - "11211:11211"

volumes:
  postgres_data:
